[workspace]
resolver = "2"

members = [
    "common",
    "ping",
    "ping_cpi",
    "fail_on_division",    
    "fail_on_division_cpi",    
]

[workspace.dependencies]
solana-program = "=1.17.31"
borsh = "^0.10"
borsh-derive = "^0.10"
